# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PawnStars-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PawnStars-iOS

  target 'PawnStars-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PawnStars-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
