# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PawnStars-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'XLPagerTabStrip', '~> 8.1'
	pod 'DLRadioButton', '~> 1.4'
	pod 'TextFieldEffects'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxDataSources', '~> 3.0'
  pod 'RxAlamofire'
  # Pods for PawnStars-iOS

  target 'PawnStars-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PawnStars-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
